stages:
  - test

test:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: test
  script:
    - cd "$CI_PROJECT_DIR/project"
    - npm ci
    - npm run dev &
    - npm run testViewless