/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bed.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bed(props) {
  const { nodes, materials } = useGLTF('/models/bed.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bed.geometry} material={nodes.bed.material} scale={0.001}/>
    </group>
  )
}

useGLTF.preload('/bed.gltf')
