/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bed_assembly.gltf 
*/

import { useGLTF } from '@react-three/drei'

export function Bed_assembly(props) {
  const { nodes, materials } = useGLTF('/models/bed_assembly.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bed_assembly.geometry} material={nodes.bed_assembly.material} scale={0.001}/>
    </group>
  )
}

useGLTF.preload('/bed_assembly.gltf')
