/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tv_wand.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tv_wand(props) {
  const { nodes, materials } = useGLTF('/models/tv_wand_white.gltf')
    console.log("MATERIALS");
    console.log(materials);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tv_wand_white.geometry} material={materials["Material.001"]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/tv_wand_white.gltf')
