/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tv_wand.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/tv_wand.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tv_wand.geometry} material={nodes.tv_wand.material} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/tv_wand.gltf')
